class MarketplaceCategory {
  final String id;
  final String name;
  final String icon;
  final List<String> subcategories;

  const MarketplaceCategory({
    required this.id,
    required this.name,
    required this.icon,
    required this.subcategories,
  });

  static const List<MarketplaceCategory> allCategories = [
    MarketplaceCategory(
      id: 'vegetables',
      name: 'Vegetables',
      icon: '🥦',
      subcategories: [
        'Leafy',
        'Root',
        'Gourd',
        'Beans',
        'Tomato',
        'Potato',
        'Onion',
        'Other',
      ],
    ),
    MarketplaceCategory(
      id: 'fruits',
      name: 'Fruits',
      icon: '🍎',
      subcategories: [
        'Citrus',
        'Tropical',
        'Berries',
        'Melons',
        'Apple',
        'Banana',
        'Mango',
        'Other',
      ],
    ),
    MarketplaceCategory(
      id: 'grains',
      name: 'Grains & Cereals',
      icon: '🌾',
      subcategories: [
        'Rice',
        'Wheat',
        'Maize',
        'Millet',
        'Barley',
        'Buckwheat',
        'Other',
      ],
    ),
    MarketplaceCategory(
      id: 'spices',
      name: 'Spices',
      icon: '🌶️',
      subcategories: [
        'Chili',
        'Ginger',
        'Garlic',
        'Turmeric',
        'Cardamom',
        'Cumin',
        'Coriander',
        'Other',
      ],
    ),
    MarketplaceCategory(
      id: 'livestock',
      name: 'Livestock',
      icon: '🐄',
      subcategories: [
        'Cattle',
        'Goat',
        'Buffalo',
        'Pig',
        'Poultry',
        'Sheep',
        'Other',
      ],
    ),
    MarketplaceCategory(
      id: 'dairy',
      name: 'Dairy',
      icon: '🥛',
      subcategories: [
        'Milk',
        'Ghee',
        'Butter',
        'Curd',
        'Cheese',
        'Paneer',
        'Other',
      ],
    ),
    MarketplaceCategory(
      id: 'seeds',
      name: 'Seeds',
      icon: '🌱',
      subcategories: [
        'Vegetable Seeds',
        'Cereal Seeds',
        'Flower Seeds',
        'Fruit Seeds',
        'Other',
      ],
    ),
    MarketplaceCategory(
      id: 'fertilizers',
      name: 'Fertilizers',
      icon: '🧪',
      subcategories: [
        'Organic',
        'Chemical',
        'Compost',
        'Bio-fertilizer',
        'Other',
      ],
    ),
    MarketplaceCategory(
      id: 'tools',
      name: 'Tools & Machinery',
      icon: '🚜',
      subcategories: [
        'Hand Tools',
        'Power Tools',
        'Tractors',
        'Irrigation',
        'Sprayers',
        'Other',
      ],
    ),
  ];
}

class MarketplaceConstants {
  static const List<String> priceUnits = [
    'kg',
    'g',
    'liter',
    'piece',
    'dozen',
    'quintal',
    'ton',
    'sack',
    'crate',
  ];

  static const List<String> qualityGrades = [
    'A+',
    'A',
    'B',
    'C',
  ];

  static const List<String> nepaliDistricts = [
    'Achham',
    'Arghakhanchi',
    'Baglung',
    'Baitadi',
    'Bajhang',
    'Bajura',
    'Banke',
    'Bara',
    'Bardiya',
    'Bhaktapur',
    'Bhojpur',
    'Chitwan',
    'Dadeldhura',
    'Dailekh',
    'Dang',
    'Darchula',
    'Dhading',
    'Dhankuta',
    'Dhanusa',
    'Dolakha',
    'Dolpa',
    'Doti',
    'Gorkha',
    'Gulmi',
    'Humla',
    'Ilam',
    'Jajarkot',
    'Jhapa',
    'Jumla',
    'Kailali',
    'Kalikot',
    'Kanchanpur',
    'Kapilvastu',
    'Kaski',
    'Kathmandu',
    'Kavrepalanchok',
    'Khotang',
    'Lalitpur',
    'Lamjung',
    'Mahottari',
    'Makwanpur',
    'Manang',
    'Morang',
    'Mugu',
    'Mustang',
    'Myagdi',
    'Nawalparasi',
    'Nuwakot',
    'Okhaldhunga',
    'Palpa',
    'Panchthar',
    'Parbat',
    'Parsa',
    'Pyuthan',
    'Ramechhap',
    'Rasuwa',
    'Rautahat',
    'Rolpa',
    'Rukum',
    'Rupandehi',
    'Salyan',
    'Sankhuwasabha',
    'Saptari',
    'Sarlahi',
    'Sindhuli',
    'Sindhupalchok',
    'Siraha',
    'Solukhumbu',
    'Sunsari',
    'Surkhet',
    'Syangja',
    'Tanahu',
    'Taplejung',
    'Terhathum',
    'Udayapur',
  ];
}
